#!/bin/bash

GitCMD='git --no-pager'
while read Branch _; do
	read EMail Date Time _ <<< "$($GitCMD log --format='%ae %ci' $Branch)"
	printf "%s %s %s %s\n" "${Branch##*/}" "$EMail" "$Date" "$Time"
done <<< "$($GitCMD branch -r --no-color)" | LC_ALL='C' sort -rk 3,4 | column -tx
