#!/bin/bash

while read -a ARRAY; do
	awk -v x="${ARRAY[0]#*/}" '
		{
			if(NR==1&&NR!~/^->$/){
				printf("%s %s %s %s\n", x, $1, $2, $3)
			}
		}
	' <<< "$(git show --format='%ae %ci' "${ARRAY[0]}")"
done <<< "$(git branch -r --no-color)" | sort -r | column -t -x
